- name: Remove apt package cache
  command: apt clean

- name: Remove apt package lists
  file:
    path: /var/lib/apt/lists
    state: absent

- name: Remove psutil (user) dependency installed for ansible dconf
  become_user: "{{ user_name }}"
  pip:
    name: psutil
    state: absent

- name: Remove cache and bash history (user)
  become_user: "{{ user_name }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.cache"
    - ".bash_history"

- name: Remove cache (root)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.bash_history"
    - "/tmp/*"
 
- name: Remove ubuntu user
  user:
    name: ubuntu
    state: absent


